#ifndef SCHEDULE_CONSTS_H
#define SCHEDULE_CONSTS_H

#define TAGNAME_SIZE 16
#define USERNAME_SIZE 20
#define TASKNAME_SIZE 256
#define TASKCONTENT_SIZE 1024

#define MAX_TAGS_PER_TASK 16
#define MAX_TAGS_PER_USER 128

#define HASHEDPASSED_SIZE 64
#define PASSWORD_SIZE 20

#endif // SCHEDULE_CONSTS_H